// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sardegna-layouts/HorizontalStrip.tsx": () => import("../components/mockups/sardegna-layouts/HorizontalStrip.tsx"),
  "./components/mockups/sardegna-layouts/MapImmersive.tsx": () => import("../components/mockups/sardegna-layouts/MapImmersive.tsx"),
  "./components/mockups/sardegna-layouts/StackedDashboard.tsx": () => import("../components/mockups/sardegna-layouts/StackedDashboard.tsx")
};
